# Generated by Django 5.1.4 on 2025-01-15 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='body',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_date',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='condition',
            field=models.CharField(choices=[('new', '新品'), ('like_new', '新品同様'), ('good', '良好'), ('fair', 'やや傷あり'), ('poor', '悪い')], default='new', max_length=10, verbose_name='グッズの状態'),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default='説明がありません', max_length=2000, verbose_name='出品グッズの説明'),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='未設定のグッズ名', max_length=100, verbose_name='出品グッズ名'),
        ),
        migrations.AddField(
            model_name='page',
            name='packaging_method',
            field=models.TextField(default='簡易包装', verbose_name='梱包方法'),
        ),
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu/picture/', verbose_name='出品画像'),
        ),
        migrations.AddField(
            model_name='page',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='個数'),
        ),
        migrations.AddField(
            model_name='page',
            name='trade_preference',
            field=models.CharField(choices=[('exchange', '交換'), ('purchase', '買取り')], default='purchase', max_length=10, verbose_name='ご希望のお取引'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='商品ID'),
        ),
    ]
