# Generated by Django 5.1.4 on 2025-01-17 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_page_body_remove_page_page_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='希望ID')),
                ('name', models.CharField(default='未設定の希望グッズ名', max_length=100, verbose_name='希望グッズ名')),
                ('details', models.TextField(default='希望内容がありません', max_length=2000, verbose_name='希望グッズの詳細')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_items', to='menu.page', verbose_name='関連する出品商品')),
            ],
        ),
    ]
