# Generated by Django 5.1.4 on 2025-01-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_wanteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='wanted_item_details',
            field=models.TextField(default='希望内容がありません', max_length=2000, verbose_name='希望グッズの詳細'),
        ),
        migrations.AddField(
            model_name='page',
            name='wanted_item_name',
            field=models.CharField(default='未設定の希望グッズ名', max_length=100, verbose_name='希望グッズ名'),
        ),
        migrations.DeleteModel(
            name='WantedItem',
        ),
    ]
