# Generated by Django 5.1.4 on 2025-01-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_page_wanted_item_details_page_wanted_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='価格'),
        ),
    ]
