# Generated by Django 5.1.4 on 2025-01-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_page_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='価格'),
        ),
    ]
